version: '3.0'

services:
  mysql:
		container_name: mysql5.7
    environment:
      MYSQL_ROOT_PASSWORD: B9tiNZ7dXrk2qwr6
    image: mysql:5.7
    network_mode: bridge
    ports:
    - 13306:3306/tcp
    restart: always
    volumes:
    - ./db:/var/lib/mysql:rw
    - ./conf/my.cnf:/etc/my.cnf:rw
    - ./init:/docker-entrypoint-initdb.d:rw
